apt install reinstall libctf0:amd64
apt install reinstall libip4tc2:amd64
apt install reinstall libksba8:amd64
apt install reinstall pinentry-curses
apt install reinstall logrotate
apt install reinstall libexpat1:amd64
apt install reinstall bash
apt install reinstall media-types
apt install reinstall cpio
apt install reinstall libpipeline1:amd64
apt install reinstall liblmdb0:amd64
apt install reinstall libtext-iconv-perl
apt install reinstall tofrodos
apt install reinstall libtirpc3:amd64
apt install reinstall libnih1
apt install reinstall xinetd
apt install reinstall libtext-charwidth-perl
apt install reinstall runit-helper
apt install reinstall libpaper1:amd64
apt install reinstall lsb-base
apt install reinstall libzstd1:amd64
apt install reinstall openssh-sftp-server
apt install reinstall tcpdump
apt install reinstall fontconfig
apt install reinstall fonts-dejavu
apt install reinstall libgnutls-dane0:amd64
apt install reinstall systemd-sysv
apt install reinstall net-tools
apt install reinstall adduser
apt install reinstall libkeyutils1:amd64
apt install reinstall odbcinst
apt install reinstall libapparmor1:amd64
apt install reinstall libc-l10n
apt install reinstall pci.ids
apt install reinstall libpsl5:amd64
apt install reinstall gettext
apt install reinstall apt
apt install reinstall libhogweed6:amd64
apt install reinstall exim4-base
apt install reinstall vim
apt install reinstall apt-utils
apt install reinstall libgpm2:amd64
apt install reinstall linux-base
apt install reinstall gpg-agent
apt install reinstall telnet
apt install reinstall mime-support
apt install reinstall initramfs-tools
apt install reinstall bsdextrautils
apt install reinstall libpam-modules:amd64
apt install reinstall wget
apt install reinstall whois
apt install reinstall unixodbc
apt install reinstall gpg-wks-client
apt install reinstall grep
apt install reinstall liblzma5:amd64
apt install reinstall openssh-server
apt install reinstall libgpg-error0:amd64
apt install reinstall python2.7
apt install reinstall procinfo
apt install reinstall console-common
apt install reinstall libicu67:amd64
apt install reinstall db-util
apt install reinstall finger
apt install reinstall bind9-libs:amd64
apt install reinstall traceroute
apt install reinstall fetchmail
apt install reinstall tar
apt install reinstall libmagic-mgc
apt install reinstall libpython2-stdlib:amd64
apt install reinstall gawk
apt install reinstall mtools
apt install reinstall psmisc
apt install reinstall iptables
apt install reinstall libip6tc2:amd64
apt install reinstall distro-info-data
apt install reinstall libpython3.9-minimal:amd64
apt install reinstall manpages
apt install reinstall liblz4-1:amd64
apt install reinstall fontconfig-config
apt install reinstall iproute2
apt install reinstall libestr0:amd64
apt install reinstall openssh-client
apt install reinstall libsnmp-base
apt install reinstall libfastjson4:amd64
apt install reinstall libssl1.1:amd64
apt install reinstall libtirpc-common
apt install reinstall libmaxminddb0:amd64
apt install reinstall libargon2-1:amd64
apt install reinstall initscripts
apt install reinstall apache2
apt install reinstall unzip
apt install reinstall perl-modules-5.32
apt install reinstall libbrotli1:amd64
apt install reinstall libfstrm0:amd64
apt install reinstall libedit2:amd64
apt install reinstall libpam-modules-bin
apt install reinstall libreadline8:amd64
apt install reinstall python3-ply
apt install reinstall libc-bin
apt install reinstall libsqlite3-0:amd64
apt install reinstall gpgsm
apt install reinstall libcbor0:amd64
apt install reinstall cron
apt install reinstall startpar
apt install reinstall ncurses-bin
apt install reinstall libffi7:amd64
apt install reinstall rsyslog
apt install reinstall cifs-utils
apt install reinstall libacl1:amd64
apt install reinstall binutils-common:amd64
apt install reinstall debian-archive-keyring
apt install reinstall libsensors-config
apt install reinstall libnghttp2-14:amd64
apt install reinstall libmagic1:amd64
apt install reinstall libunistring2:amd64
apt install reinstall libsmartcols1:amd64
apt install reinstall libapr1:amd64
apt install reinstall less
apt install reinstall libdns-export1110
apt install reinstall fonts-freefont-ttf
apt install reinstall sasl2-bin
apt install reinstall isc-dhcp-client
apt install reinstall libctf-nobfd0:amd64
apt install reinstall libldap-2.4-2:amd64
apt install reinstall gettext-base
apt install reinstall libustr-1.0-1:amd64
apt install reinstall m4
apt install reinstall libgcrypt20:amd64
apt install reinstall screen
apt install reinstall debconf-i18n
apt install reinstall libnftnl11:amd64
apt install reinstall coreutils
apt install reinstall rpcbind
apt install reinstall zlib1g:amd64
apt install reinstall libnpth0:amd64
apt install reinstall libcrypt1:amd64
apt install reinstall python3
apt install reinstall systemd
apt install reinstall snmp
apt install reinstall libidn2-0:amd64
apt install reinstall libcom-err2:amd64
apt install reinstall binutils
apt install reinstall file
apt install reinstall libaprutil1-ldap:amd64
apt install reinstall kmod
apt install reinstall libassuan0:amd64
apt install reinstall libgomp1:amd64
apt install reinstall diffutils
apt install reinstall apache2-bin
apt install reinstall iputils-arping
apt install reinstall bzip2
apt install reinstall ldap-utils
apt install reinstall locales
apt install reinstall libaprutil1-dbd-sqlite3:amd64
apt install reinstall man-db
apt install reinstall libaudit-common
apt install reinstall libasprintf0v5:amd64
apt install reinstall libgcc-s1:amd64
apt install reinstall libncurses5:amd64
apt install reinstall libtext-wrapi18n-perl
apt install reinstall libprotobuf-c1:amd64
apt install reinstall syslinux
apt install reinstall python2
apt install reinstall libsemanage-common
apt install reinstall libwbclient0:amd64
apt install reinstall libseccomp2:amd64
apt install reinstall dselect
apt install reinstall xxd
apt install reinstall libsystemd0:amd64
apt install reinstall libcap2:amd64
apt install reinstall debconf
apt install reinstall libjansson4:amd64
apt install reinstall acl
apt install reinstall libkrb5support0:amd64
apt install reinstall dns-root-data
apt install reinstall libsasl2-modules-db:amd64
apt install reinstall libpython2.7-stdlib:amd64
apt install reinstall tzdata
apt install reinstall libcap2-bin
apt install reinstall bind9-utils
apt install reinstall libtalloc2:amd64
apt install reinstall makedev
apt install reinstall perl-base
apt install reinstall libselinux1:amd64
apt install reinstall dirmngr
apt install reinstall console-data
apt install reinstall ca-certificates
apt install reinstall cracklib-runtime
apt install reinstall hostname
apt install reinstall libklibc:amd64
apt install reinstall gcc-10-base:amd64
apt install reinstall libpcre3:amd64
apt install reinstall libcap-ng0:amd64
apt install reinstall perl
apt install reinstall exim4
apt install reinstall libsnmp40:amd64
apt install reinstall libisc-export1105:amd64
apt install reinstall ncurses-base
apt install reinstall libunbound8:amd64
apt install reinstall libgnutls30:amd64
apt install reinstall libext2fs2:amd64
apt install reinstall libuv1:amd64
apt install reinstall libpam0g:amd64
apt install reinstall libpython2.7-minimal:amd64
apt install reinstall vim-common
apt install reinstall expat
apt install reinstall libslang2:amd64
apt install reinstall libtevent0:amd64
apt install reinstall apache2-doc
apt install reinstall libfreetype6:amd64
apt install reinstall libnettle8:amd64
apt install reinstall libpcap0.8:amd64
apt install reinstall libwrap0:amd64
apt install reinstall make
apt install reinstall libmpfr6:amd64
apt install reinstall gnupg-l10n
apt install reinstall ssl-cert
apt install reinstall ed
apt install reinstall dialog
apt install reinstall librtmp1:amd64
apt install reinstall libapt-pkg6.0:amd64
apt install reinstall python2.7-minimal
apt install reinstall libidn11:amd64
apt install reinstall wide-dhcpv6-client
apt install reinstall ifupdown
apt install reinstall libgmp10:amd64
apt install reinstall init-system-helpers
apt install reinstall libncurses6:amd64
apt install reinstall libdbus-1-3:amd64
apt install reinstall dbus
apt install reinstall libsigsegv2:amd64
apt install reinstall xz-utils
apt install reinstall sed
apt install reinstall libp11-kit0:amd64
apt install reinstall debconf-utils
apt install reinstall libaudit1:amd64
apt install reinstall libpng16-16:amd64
apt install reinstall gzip
apt install reinstall libmnl0:amd64
apt install reinstall systemd-timesyncd
apt install reinstall db5.3-util
apt install reinstall libgssapi-krb5-2:amd64
apt install reinstall udev
apt install reinstall libuuid1:amd64
apt install reinstall libevent-2.1-7:amd64
apt install reinstall patch
apt install reinstall ftp
apt install reinstall sudo
apt install reinstall fonts-dejavu-core
apt install reinstall libgdbm-compat4:amd64
apt install reinstall lzma
apt install reinstall util-linux
apt install reinstall libodbc1:amd64
apt install reinstall python2-minimal
apt install reinstall libfl2:amd64
apt install reinstall ucf
apt install reinstall libsensors5:amd64
apt install reinstall libpcre2-8-0:amd64
apt install reinstall insserv
apt install reinstall libncursesw6:amd64
apt install reinstall libk5crypto3:amd64
apt install reinstall libxtables12:amd64
apt install reinstall lynx-common
apt install reinstall libperl5.32:amd64
apt install reinstall libltdl7:amd64
apt install reinstall quota
apt install reinstall logsave
apt install reinstall libsasl2-2:amd64
apt install reinstall dpkg
apt install reinstall lsof
apt install reinstall libc6:amd64
apt install reinstall libcrack2:amd64
apt install reinstall libfdisk1:amd64
apt install reinstall liblognorm5:amd64
apt install reinstall gpg-wks-server
apt install reinstall libudev1:amd64
apt install reinstall libutempter0:amd64
apt install reinstall memtester
apt install reinstall libsepol1:amd64
apt install reinstall procmail
apt install reinstall libpci3:amd64
apt install reinstall libdevmapper1.02.1:amd64
apt install reinstall fonts-dejavu-extra
apt install reinstall libmd0:amd64
apt install reinstall passwd
apt install reinstall findutils
apt install reinstall mount
apt install reinstall dmsetup
apt install reinstall sensible-utils
apt install reinstall exim4-config
apt install reinstall uuid-runtime
apt install reinstall libnetfilter-conntrack3:amd64
apt install reinstall groff-base
apt install reinstall gpgv
apt install reinstall libmount1:amd64
apt install reinstall bind9
apt install reinstall libnfnetlink0:amd64
apt install reinstall libxxhash0:amd64
apt install reinstall libuchardet0:amd64
apt install reinstall liblua5.3-0:amd64
apt install reinstall procps
apt install reinstall libnl-genl-3-200:amd64
apt install reinstall libattr1:amd64
apt install reinstall libnsl2:amd64
apt install reinstall libnl-3-200:amd64
apt install reinstall libmpdec3:amd64
apt install reinstall gpgconf
apt install reinstall sysvinit-utils
apt install reinstall gnupg
apt install reinstall libtasn1-6:amd64
apt install reinstall libcurl4:amd64
apt install reinstall libcryptsetup12:amd64
apt install reinstall sysv-rc
apt install reinstall kbd
apt install reinstall libssh2-1:amd64
apt install reinstall netbase
apt install reinstall python3-minimal
apt install reinstall isc-dhcp-common
apt install reinstall debianutils
apt install reinstall mlocate
apt install reinstall libkrb5-3:amd64
apt install reinstall apache2-data
apt install reinstall libfontconfig1:amd64
apt install reinstall lynx
apt install reinstall python3.9-minimal
apt install reinstall install-info
apt install reinstall libdebconfclient0:amd64
apt install reinstall base-files
apt install reinstall sharutils
apt install reinstall odbcinst1debian2:amd64
apt install reinstall libbinutils:amd64
apt install reinstall vim-runtime
apt install reinstall lsb-release
apt install reinstall libfido2-1:amd64
apt install reinstall libbpf0:amd64
apt install reinstall initramfs-tools-core
apt install reinstall libbz2-1.0:amd64
apt install reinstall klibc-utils
apt install reinstall libsemanage1:amd64
apt install reinstall bind9-host
apt install reinstall openssl
apt install reinstall libbsd0:amd64
apt install reinstall libtinfo5:amd64
apt install reinstall mailcap
apt install reinstall libelf1:amd64
apt install reinstall psutils
apt install reinstall base-passwd
apt install reinstall iputils-ping
apt install reinstall libjson-c5:amd64
apt install reinstall readline-common
apt install reinstall libpam-runtime
apt install reinstall libdb5.3:amd64
apt install reinstall libxml2:amd64
apt install reinstall pwgen
apt install reinstall tcsh
apt install reinstall libblkid1:amd64
apt install reinstall libnih-dbus1
apt install reinstall exim4-daemon-light
apt install reinstall libstdc++6:amd64
apt install reinstall info
apt install reinstall liblocale-gettext-perl
apt install reinstall gpg
apt install reinstall libprocps8:amd64
apt install reinstall dash
apt install reinstall iputils-tracepath
apt install reinstall python3.9
apt install reinstall rsync
apt install reinstall libkmod2:amd64
apt install reinstall libpython3.9-stdlib:amd64
apt install reinstall libpython3-stdlib:amd64
apt install reinstall libgdbm6:amd64
apt install reinstall libtinfo6:amd64
apt install reinstall libpopt0:amd64
apt install reinstall gnupg-utils
apt install reinstall python-is-python2
apt install reinstall apache2-utils
apt install reinstall binutils-x86-64-linux-gnu
apt install reinstall ncurses-term
apt install reinstall libaprutil1:amd64
apt install reinstall login
