apt reinstall libctf0:amd64
apt reinstall libip4tc2:amd64
apt reinstall libksba8:amd64
apt reinstall pinentry-curses
apt reinstall logrotate
apt reinstall libexpat1:amd64
apt reinstall bash
apt reinstall media-types
apt reinstall cpio
apt reinstall libpipeline1:amd64
apt reinstall liblmdb0:amd64
apt reinstall libtext-iconv-perl
apt reinstall tofrodos
apt reinstall libtirpc3:amd64
apt reinstall libnih1
apt reinstall xinetd
apt reinstall libtext-charwidth-perl
apt reinstall runit-helper
apt reinstall libpaper1:amd64
apt reinstall lsb-base
apt reinstall libzstd1:amd64
apt reinstall openssh-sftp-server
apt reinstall tcpdump
apt reinstall fontconfig
apt reinstall fonts-dejavu
apt reinstall libgnutls-dane0:amd64
apt reinstall systemd-sysv
apt reinstall net-tools
apt reinstall adduser
apt reinstall libkeyutils1:amd64
apt reinstall odbcinst
apt reinstall libapparmor1:amd64
apt reinstall libc-l10n
apt reinstall pci.ids
apt reinstall libpsl5:amd64
apt reinstall gettext
apt reinstall apt
apt reinstall libhogweed6:amd64
apt reinstall exim4-base
apt reinstall vim
apt reinstall apt-utils
apt reinstall libgpm2:amd64
apt reinstall linux-base
apt reinstall gpg-agent
apt reinstall telnet
apt reinstall mime-support
apt reinstall initramfs-tools
apt reinstall bsdextrautils
apt reinstall libpam-modules:amd64
apt reinstall wget
apt reinstall whois
apt reinstall unixodbc
apt reinstall gpg-wks-client
apt reinstall grep
apt reinstall liblzma5:amd64
apt reinstall openssh-server
apt reinstall libgpg-error0:amd64
apt reinstall python2.7
apt reinstall procinfo
apt reinstall console-common
apt reinstall libicu67:amd64
apt reinstall db-util
apt reinstall finger
apt reinstall bind9-libs:amd64
apt reinstall traceroute
apt reinstall fetchmail
apt reinstall tar
apt reinstall libmagic-mgc
apt reinstall libpython2-stdlib:amd64
apt reinstall gawk
apt reinstall mtools
apt reinstall psmisc
apt reinstall iptables
apt reinstall libip6tc2:amd64
apt reinstall distro-info-data
apt reinstall libpython3.9-minimal:amd64
apt reinstall manpages
apt reinstall liblz4-1:amd64
apt reinstall fontconfig-config
apt reinstall iproute2
apt reinstall libestr0:amd64
apt reinstall openssh-client
apt reinstall libsnmp-base
apt reinstall libfastjson4:amd64
apt reinstall libssl1.1:amd64
apt reinstall libtirpc-common
apt reinstall libmaxminddb0:amd64
apt reinstall libargon2-1:amd64
apt reinstall initscripts
apt reinstall apache2
apt reinstall unzip
apt reinstall perl-modules-5.32
apt reinstall libbrotli1:amd64
apt reinstall libfstrm0:amd64
apt reinstall libedit2:amd64
apt reinstall libpam-modules-bin
apt reinstall libreadline8:amd64
apt reinstall python3-ply
apt reinstall libc-bin
apt reinstall libsqlite3-0:amd64
apt reinstall gpgsm
apt reinstall libcbor0:amd64
apt reinstall cron
apt reinstall startpar
apt reinstall ncurses-bin
apt reinstall libffi7:amd64
apt reinstall rsyslog
apt reinstall cifs-utils
apt reinstall libacl1:amd64
apt reinstall binutils-common:amd64
apt reinstall debian-archive-keyring
apt reinstall libsensors-config
apt reinstall libnghttp2-14:amd64
apt reinstall libmagic1:amd64
apt reinstall libunistring2:amd64
apt reinstall libsmartcols1:amd64
apt reinstall libapr1:amd64
apt reinstall less
apt reinstall libdns-export1110
apt reinstall fonts-freefont-ttf
apt reinstall sasl2-bin
apt reinstall isc-dhcp-client
apt reinstall libctf-nobfd0:amd64
apt reinstall libldap-2.4-2:amd64
apt reinstall gettext-base
apt reinstall libustr-1.0-1:amd64
apt reinstall m4
apt reinstall libgcrypt20:amd64
apt reinstall screen
apt reinstall debconf-i18n
apt reinstall libnftnl11:amd64
apt reinstall coreutils
apt reinstall rpcbind
apt reinstall zlib1g:amd64
apt reinstall libnpth0:amd64
apt reinstall libcrypt1:amd64
apt reinstall python3
apt reinstall systemd
apt reinstall snmp
apt reinstall libidn2-0:amd64
apt reinstall libcom-err2:amd64
apt reinstall binutils
apt reinstall file
apt reinstall libaprutil1-ldap:amd64
apt reinstall kmod
apt reinstall libassuan0:amd64
apt reinstall libgomp1:amd64
apt reinstall diffutils
apt reinstall apache2-bin
apt reinstall iputils-arping
apt reinstall bzip2
apt reinstall ldap-utils
apt reinstall locales
apt reinstall libaprutil1-dbd-sqlite3:amd64
apt reinstall man-db
apt reinstall libaudit-common
apt reinstall libasprintf0v5:amd64
apt reinstall libgcc-s1:amd64
apt reinstall libncurses5:amd64
apt reinstall libtext-wrapi18n-perl
apt reinstall libprotobuf-c1:amd64
apt reinstall syslinux
apt reinstall python2
apt reinstall libsemanage-common
apt reinstall libwbclient0:amd64
apt reinstall libseccomp2:amd64
apt reinstall dselect
apt reinstall xxd
apt reinstall libsystemd0:amd64
apt reinstall libcap2:amd64
apt reinstall debconf
apt reinstall libjansson4:amd64
apt reinstall acl
apt reinstall libkrb5support0:amd64
apt reinstall dns-root-data
apt reinstall libsasl2-modules-db:amd64
apt reinstall libpython2.7-stdlib:amd64
apt reinstall tzdata
apt reinstall libcap2-bin
apt reinstall bind9-utils
apt reinstall libtalloc2:amd64
apt reinstall makedev
apt reinstall perl-base
apt reinstall libselinux1:amd64
apt reinstall dirmngr
apt reinstall console-data
apt reinstall ca-certificates
apt reinstall cracklib-runtime
apt reinstall hostname
apt reinstall libklibc:amd64
apt reinstall gcc-10-base:amd64
apt reinstall libpcre3:amd64
apt reinstall libcap-ng0:amd64
apt reinstall perl
apt reinstall exim4
apt reinstall libsnmp40:amd64
apt reinstall libisc-export1105:amd64
apt reinstall ncurses-base
apt reinstall libunbound8:amd64
apt reinstall libgnutls30:amd64
apt reinstall libext2fs2:amd64
apt reinstall libuv1:amd64
apt reinstall libpam0g:amd64
apt reinstall libpython2.7-minimal:amd64
apt reinstall vim-common
apt reinstall expat
apt reinstall libslang2:amd64
apt reinstall libtevent0:amd64
apt reinstall apache2-doc
apt reinstall libfreetype6:amd64
apt reinstall libnettle8:amd64
apt reinstall libpcap0.8:amd64
apt reinstall libwrap0:amd64
apt reinstall make
apt reinstall libmpfr6:amd64
apt reinstall gnupg-l10n
apt reinstall ssl-cert
apt reinstall ed
apt reinstall dialog
apt reinstall librtmp1:amd64
apt reinstall libapt-pkg6.0:amd64
apt reinstall python2.7-minimal
apt reinstall libidn11:amd64
apt reinstall wide-dhcpv6-client
apt reinstall ifupdown
apt reinstall libgmp10:amd64
apt reinstall init-system-helpers
apt reinstall libncurses6:amd64
apt reinstall libdbus-1-3:amd64
apt reinstall dbus
apt reinstall libsigsegv2:amd64
apt reinstall xz-utils
apt reinstall sed
apt reinstall libp11-kit0:amd64
apt reinstall debconf-utils
apt reinstall libaudit1:amd64
apt reinstall libpng16-16:amd64
apt reinstall gzip
apt reinstall libmnl0:amd64
apt reinstall systemd-timesyncd
apt reinstall db5.3-util
apt reinstall libgssapi-krb5-2:amd64
apt reinstall udev
apt reinstall libuuid1:amd64
apt reinstall libevent-2.1-7:amd64
apt reinstall patch
apt reinstall ftp
apt reinstall sudo
apt reinstall fonts-dejavu-core
apt reinstall libgdbm-compat4:amd64
apt reinstall lzma
apt reinstall util-linux
apt reinstall libodbc1:amd64
apt reinstall python2-minimal
apt reinstall libfl2:amd64
apt reinstall ucf
apt reinstall libsensors5:amd64
apt reinstall libpcre2-8-0:amd64
apt reinstall insserv
apt reinstall libncursesw6:amd64
apt reinstall libk5crypto3:amd64
apt reinstall libxtables12:amd64
apt reinstall lynx-common
apt reinstall libperl5.32:amd64
apt reinstall libltdl7:amd64
apt reinstall quota
apt reinstall logsave
apt reinstall libsasl2-2:amd64
apt reinstall dpkg
apt reinstall lsof
apt reinstall libc6:amd64
apt reinstall libcrack2:amd64
apt reinstall libfdisk1:amd64
apt reinstall liblognorm5:amd64
apt reinstall gpg-wks-server
apt reinstall libudev1:amd64
apt reinstall libutempter0:amd64
apt reinstall memtester
apt reinstall libsepol1:amd64
apt reinstall procmail
apt reinstall libpci3:amd64
apt reinstall libdevmapper1.02.1:amd64
apt reinstall fonts-dejavu-extra
apt reinstall libmd0:amd64
apt reinstall passwd
apt reinstall findutils
apt reinstall mount
apt reinstall dmsetup
apt reinstall sensible-utils
apt reinstall exim4-config
apt reinstall uuid-runtime
apt reinstall libnetfilter-conntrack3:amd64
apt reinstall groff-base
apt reinstall gpgv
apt reinstall libmount1:amd64
apt reinstall bind9
apt reinstall libnfnetlink0:amd64
apt reinstall libxxhash0:amd64
apt reinstall libuchardet0:amd64
apt reinstall liblua5.3-0:amd64
apt reinstall procps
apt reinstall libnl-genl-3-200:amd64
apt reinstall libattr1:amd64
apt reinstall libnsl2:amd64
apt reinstall libnl-3-200:amd64
apt reinstall libmpdec3:amd64
apt reinstall gpgconf
apt reinstall sysvinit-utils
apt reinstall gnupg
apt reinstall libtasn1-6:amd64
apt reinstall libcurl4:amd64
apt reinstall libcryptsetup12:amd64
apt reinstall sysv-rc
apt reinstall kbd
apt reinstall libssh2-1:amd64
apt reinstall netbase
apt reinstall python3-minimal
apt reinstall isc-dhcp-common
apt reinstall debianutils
apt reinstall mlocate
apt reinstall libkrb5-3:amd64
apt reinstall apache2-data
apt reinstall libfontconfig1:amd64
apt reinstall lynx
apt reinstall python3.9-minimal
apt reinstall-info
apt reinstall libdebconfclient0:amd64
apt reinstall base-files
apt reinstall sharutils
apt reinstall odbcinst1debian2:amd64
apt reinstall libbinutils:amd64
apt reinstall vim-runtime
apt reinstall lsb-release
apt reinstall libfido2-1:amd64
apt reinstall libbpf0:amd64
apt reinstall initramfs-tools-core
apt reinstall libbz2-1.0:amd64
apt reinstall klibc-utils
apt reinstall libsemanage1:amd64
apt reinstall bind9-host
apt reinstall openssl
apt reinstall libbsd0:amd64
apt reinstall libtinfo5:amd64
apt reinstall mailcap
apt reinstall libelf1:amd64
apt reinstall psutils
apt reinstall base-passwd
apt reinstall iputils-ping
apt reinstall libjson-c5:amd64
apt reinstall readline-common
apt reinstall libpam-runtime
apt reinstall libdb5.3:amd64
apt reinstall libxml2:amd64
apt reinstall pwgen
apt reinstall tcsh
apt reinstall libblkid1:amd64
apt reinstall libnih-dbus1
apt reinstall exim4-daemon-light
apt reinstall libstdc++6:amd64
apt reinstall info
apt reinstall liblocale-gettext-perl
apt reinstall gpg
apt reinstall libprocps8:amd64
apt reinstall dash
apt reinstall iputils-tracepath
apt reinstall python3.9
apt reinstall rsync
apt reinstall libkmod2:amd64
apt reinstall libpython3.9-stdlib:amd64
apt reinstall libpython3-stdlib:amd64
apt reinstall libgdbm6:amd64
apt reinstall libtinfo6:amd64
apt reinstall libpopt0:amd64
apt reinstall gnupg-utils
apt reinstall python-is-python2
apt reinstall apache2-utils
apt reinstall binutils-x86-64-linux-gnu
apt reinstall ncurses-term
apt reinstall libaprutil1:amd64
apt reinstall login
